### PR TITLE
Periodic Mean Smoothing

### PR DESCRIPTION
**Pull request by hntd187**
Since Greg and I agreed that it would be fruitless to try and chase the numeric precision I added in the periodic mean smoothing. I'm including 2 plots of the difference in it for comparison purposes.

### CODE REVIEW

**Comment by hntd187** [comment]
Duh, sorry, I'll fix these merge conflicts.

**Comment by hntd187** [comment]
Hmmm, okay what the hell is going on here? Should I reopen this?

**Comment by brandtg** [comment]
You might need to sync with master and rebase. This article might help https://help.github.com/articles/syncing-a-fork/

Sorry I had to change the name of some classes to be consistent with the style guide, so that may have screwed with things.

It might be easier to just do the sync then create a new pull request with your commit.

**Comment by hntd187** [comment]
Yea, I'm not sure what happened there, I guess I had to update the git index for the files, but all sorted out now. Yea, I realized to change the files and I updated them to find it still complaining about merge conflicts, but I suppose I had to also merge the git stuff on the internal so that git knew about the new files.

**Comment by brandtg** [comment]
Looks good to me

**Pull request merged**
